CREATE TYPE Address AS
(City VARCHAR,
Street VARCHAR,
House SMALLINT,
Flat SMALLINT);

CREATE DOMAIN Post CHAR(9)
        CONSTRAINT Valid_Posts
        CHECK(VALUE IN('Зав. каф.','Проф.','Доц.','Ст. преп.', 'Преп.','Ассист.'));

CREATE SEQUENCE letters_kod;

CREATE TABLE Department
(DeptKod INTEGER CHECK(DeptKod>0) PRIMARY KEY,
DeptName CHAR(40) NOT NULL UNIQUE,
PKod     INTEGER REFERENCES Department(DeptKod));

CREATE TABLE Lecturer
(Kod            INTEGER CHECK(Kod>0) PRIMARY KEY,
SecondName      CHAR(30) NOT NULL,
FirstName       CHAR(20) NOT NULL,
Patronymic      CHAR(30) NOT NULL,
Job             Post NOT NULL,
DeptKod         INTEGER REFERENCES Department(DeptKod),
HireDate        DATE,
Salary          NUMERIC(5));

CREATE TABLE SalaryIncrements
(LKod   INTEGER CHECK(LKod>0)
        PRIMARY KEY REFERENCES Lecturer(Kod),
LongevityInc    NUMERIC(5) DEFAULT 0,
DegreeInc       NUMERIC(5) DEFAULT 0,
TitleInc        NUMERIC(5) DEFAULT 0,
SpecialInc      NUMERIC(5) DEFAULT 0);

CREATE TABLE Speciality
(SpKod CHAR(10) PRIMARY KEY
                CHECK(SpKod LIKE '_.________'),
ScDirect CHAR(25) NOT NULL,
SpName CHAR(40) NOT NULL UNIQUE,
Spec CHAR(2) NOT NULL UNIQUE
CHECK(Spec IN('ОИ','ОМ','ОС','ОП','АІ','АС','АК','АП')));

CREATE TABLE Student
(Kod INTEGER CHECK(Kod>0) PRIMARY KEY,
SecondName CHAR(30) NOT NULL,
FirstName CHAR(20) NOT NULL,
Patronymic CHAR(20),
SNum SMALLINT NOT NULL,
Spec    CHAR(2) NOT NULL
        CHECK(Spec IN('ОИ','ОМ','ОС','ОП','АІ','АС','АК','АП'))
        REFERENCES Speciality (Spec),
GNum INTEGER NOT NULL,
Address Address,
Email CHAR(30),
UNIQUE(Spec, GNum, SNum));

CREATE TABLE Dwlist
(DpKod SERIAL CHECK(DpKod>0) PRIMARY KEY,
DpName VARCHAR(100) UNIQUE,
LKod INTEGER REFERENCES Lecturer(Kod));

CREATE TABLE DWExec
(SKod INTEGER REFERENCES Student(Kod),
DpKod INTEGER REFERENCES Dwlist (DpKod) UNIQUE,
PRIMARY KEY (SKod, DpKod));

CREATE TABLE Letters
(Ltkod INTEGER CHECK(Ltkod>0) PRIMARY KEY
        DEFAULT NEXTVAL('letters_kod'),
Kod INTEGER REFERENCES Student (Kod),
Content VARCHAR);

CREATE TABLE Discipline
(DKod INTEGER CHECK(DKod>0) PRIMARY KEY,
DName CHAR(30),
Numhours INTEGER,
Numsemester INTEGER,
Coursework BOOLEAN,
Cursemester INTEGER);

CREATE TABLE Rating
(Kod INTEGER NOT NULL REFERENCES Student(Kod),
DKod INTEGER REFERENCES Discipline(DKod),
Mark    INTEGER DEFAULT 0
        CHECK (Mark BETWEEN 0 AND 100),
MDate DATE,
PRIMARY KEY (Kod, DKod));

ALTER TABLE Speciality
DROP CONSTRAINT speciality_pkey,
ALTER COLUMN SpKod DROP NOT NULL,
DROP CONSTRAINT speciality_spname_key,
ADD COLUMN      SpIndex SMALLINT PRIMARY KEY
                GENERATED BY DEFAULT AS IDENTITY,
ADD COLUMN SpKodNew SMALLINT;




INSERT INTO Department
VALUES (1, 'ИБЭИТ', NULL),
       (2, 'ЭКИТ',  1),
       (3, 'УАА',   2),
       (4, 'ИКС',   NULL),
       (5, 'СПО',   4),
       (6, 'ИС',    4);

INSERT INTO Lecturer
VALUES  (1, 'Малахов', 'Евгений', 'Валериевич', 'Зав. каф.', 2, '1990-09-01', 1500),
        (2, 'Востров', 'Георгий', 'Николаевич', 'Доц.', 4, '1982-09-01', 1100),
        (3, 'Чугунов', 'Анатолий', 'Анатолиевич', 'Доц.', 2, '1985-09-01', 1250),
        (4, 'Погорецкая', 'Валентина', 'Яковлевна', 'Доц.', 2, '1980-09-01', 1000),
        (5, 'Юхименко', 'Бируте', 'Иоановна', 'Проф.', 3, '1982-09-01', 1300);

INSERT INTO Student
VALUES
        (2, 'Арсирий', 'Елена', 'Александровка', 17, 'ОИ', 943, '("г.Одесса","ул.Вторая", 3,1)', 'arsiriy@mail.ru'),
        (3, 'Любченко', 'Вера', 'Викторовна', 3, 'ОС', 102, '("г.Одесса","ул.1-го Мая", 5,1)', 'lubchenko@te.net.ua'),
        (4, 'Филатова', 'Татьяна', 'Вячеславовна', 15, 'ОИ', 943, '("г.Одесса","ул.Неизвестног", 15,1)', 'filatova@mail.ru'),
        (5, 'Журан', 'Елена', 'Анатолиевна', 4, 'ОП', 971, '("г.Одесса","ул.Обычная", 45,4)', 'zhuran@ukr.net'),
        (6, 'Микулинская', 'Мария', 'Геннадиевна', 5, 'ОП', 970, '("г.Одесса","ул.Розовая", 67,8)', 'mmg12345@te.net.ua'),
        (7, 'Блажко', 'Александр', 'Анатолиевич', 12, 'АС', 954, '("г.Одесса","ул.Местная", 2,4)', 'blazko@ukr.net'),
        (8, 'Филиппова', 'Светлана', 'Валериевна', 11, 'ОМ', 951, '("г.Одесса","ул.Крайняя", 56,9)', 'filyppova@mail.ru');
